version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3.1

commands:
  install_hadolint:
    description: "Install hadolint v2.12.0"
    steps:
      - run:
          command: |
            wget -O ~/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            sudo chmod +x ~/hadolint

jobs:
  lint:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - restore_cache:
          keys: [dependencies]
      - run:
          name: install hadolint
          command: |
            wget -O ~/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            sudo chmod +x ~/hadolint
      - run:
          name: install node_modules
          command: |
            npm install
      - run:
          name: Lint Dockerfile
          command: |
            ~/hadolint Dockerfile
      - save_cache:
          paths: [node_modules]
          key: dependencies    

  deploy-application:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      docker-image-name:
        description: |
          Name of the docker image to be deployed
        type: string
      version-info:
        description: |
          App version information
        type: string
      aws-region:
        description: |
          AWS region
        type: string
        default: ""
    steps:
      - checkout
      - run:
          name: Create deployment manifest
          command: |
            BUILD_DATE=$(date '+%Y%m%d%H%M%S')
            cat deployment/app-deployment.yaml.template |\
               sed "s|DOCKER_IMAGE_NAME|<< parameters.docker-image-name >>|\
                g;s|BUILD_DATE_VALUE|$BUILD_DATE|g;s|VERSION_INFO_VALUE|\
                << parameters.version-info >>|g" > deployment/app-deployment.yaml
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          aws-region: << parameters.aws-region >>
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/app-deployment.yaml"
          get-rollout-status: true
          resource-name: deployment/app
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/app-service.yaml"

  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: "tests/nginx-deployment/deployment.yaml"
          resource-name: "deployment/nginx-deployment"
          get-rollout-status: true
          show-kubectl-command: true
    
workflows:
  default:
    jobs:
      - lint
      - aws-ecr/build-and-push-image:
          name: 'build-and-push-image'
          context: udacity
          create-repo: true
          dockerfile: Dockerfile
          path: .
          repo: circleci-ecr
          tag: "udacity-project-${CIRCLE_WORKFLOW_ID:0:7}"
          requires:
            - lint
      - aws-eks/create-cluster:
          cluster-name: eks-orb-circle-ci
          aws-region: $AWS_DEFAULT_REGION
          requires: 
            - build-and-push-image      
      - deploy-application:
          cluster-name: eks-orb-circle-ci
          aws-region: $AWS_DEFAULT_REGION
          docker-image-name: "${AWS_ECR_URL}/circleci-ecr:udacity-project-${CIRCLE_WORKFLOW_ID:0:7}"
          version-info: "udacity-project-${CIRCLE_WORKFLOW_ID:0:7}"
          requires:
            - aws-eks/create-cluster