apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::069326107975:role/eksctl-eks-orb-circle-ci-nodegrou-NodeInstanceRole-QB8QQ8PJH75P
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes